### ISSUE TITLE
Not Pure Python as claimed

### ISSUE THREAD

**Issue by Armored-Dragon** [TiberiumPY/puremine#10]
Quarry depends on many modules, and one of its dependencies requires native extensions.
From what I remember, the problematic module is Cryptography.

As we may know, MC's protocol is encrypted when online mode is on and authentication was successful, and this server needs to implement that with an encryption library.

This would be extremely slow in pure Python. Cryptography links to OpenSSL for speed. Maybe add a note about this?

**Comment by TiberiumPY** [comment]
https://github.com/pyca/cryptography
Cryptography is implemented using cffi bindings to OpenSSL, and almost everything is Python. I intented puremine to be ran with PyPy (python interpreter with JIT), because PyPy is better with long-running applications.

**Comment by TiberiumPY** [comment]
Close;
