### ISSUE TITLE
Lets collaborate!

### ISSUE THREAD

**Issue by SkippsDev** [TiberiumPY/puremine#6]
Aye, i'm BonemealPioneer from Redstone-Crafted (https://github.com/Redstone-Crafted/Redstone)
I seen this project and seems you really want to write a minecraft server in python, i've done just that implementing my custom completely from scratch server, i'm looking for others to help maintain it. If you're interested it would be great to have you on the team!

**Comment by TiberiumPY** [comment]
I would like to help you, but I'm somewhat noob in Python!

**Comment by TiberiumPY** [comment]
closed
